apiVersion: v1
kind: Service
metadata:
  name: myubuntu-nginx
  namespace: jenkin
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: |
      {
        "type": "public",
        "bandwidth_name": "cce-bandwidth",
        "bandwidth_chargemode": "traffic",
        "bandwidth_size": 5,
        "bandwidth_sharetype": "PER"
      }
spec:
  type: LoadBalancer
  selector:
    app: myubuntu-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
